print("Getting to know you!")
myName = input("What's your name? ")
myFood = input("What's your favorite food? ")
myMusic = input("What's your favorite music? ")
myHome = input("Where do you live? ")
print()
print("So your name is")
print(myName)
print("and you are hungry for")
print(myFood)
print("and you like to groove to")
print(myMusic)
print("and you live in the amazing")
print(myHome)
print("")